# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o307yUy0b597UQCkPnlmetdgYce2-B79
"""

import pandas as pd
titanic=pd.read_csv("/content/Titanic-Dataset (1).csv")
print(titanic)

kimdir=titanic[titanic["Name"]=="Allen, Mr. William Henry"]
print(kimdir)

kimdir1=titanic[titanic["Name"]=="Dooley, Mr. Patrick"]
print (kimdir1)